# ip_proof_dashboard.py (Streamlit App with Auth, Stripe, Dashboard)

import streamlit as st
import hashlib
import datetime
from fpdf import FPDF
import io
import pandas as pd

import requests
from dotenv import load_dotenv
import streamlit as st
import os

import streamlit as st
import hashlib, datetime, io, os
import psycopg2, pandas as pd, stripe, requests
from dotenv import load_dotenv
from fpdf import FPDF
from streamlit_auth0 import login_button


if page == "📤 Upload File":
    st.title("📜 IP Proof & Timestamp Generator")
    # ... upload code ...

elif page == "📊 Dashboard":
    st.title("📊 Certificate Dashboard")
    # ... dashboard code ...

def add_field(pdf, label, value, font_size=12, multiline=False):
    pdf.set_font("Helvetica", style="B", size=font_size)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, f"{label}", ln=True)
    pdf.set_font("Helvetica", size=font_size)
    pdf.set_text_color(80, 80, 80)
    if multiline:
        pdf.multi_cell(0, 8, value)
    else:
        pdf.cell(0, 8, value, ln=True)
    pdf.ln(4)

# ----- PAGE 1: UPLOAD FILE -----
if page == "📤 Upload File":
    st.title("📜 IP Proof & Timestamp Generator")

    uploaded_file = st.file_uploader("Upload your file (any type)", type=None)

    if uploaded_file:
        file_bytes = uploaded_file.read()
        file_name = uploaded_file.name
        file_hash = hashlib.sha256(file_bytes).hexdigest()
        timestamp = datetime.datetime.utcnow()

        # Generate PDF
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", style="B", size=18)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 15, "IP Timestamp Proof Certificate", ln=True, align="C")
        pdf.line(10, 25, 200, 25)
        pdf.ln(15)
        add_field(pdf, "Filename:", file_name)
        add_field(pdf, "Hash (SHA256):", file_hash, font_size=10, multiline=True)
        add_field(pdf, "Timestamp:", timestamp.strftime("%Y-%m-%d %H:%M:%S UTC"))
        add_field(pdf, "User Gmail:", st.session_state.email)
        pdf.ln(5)
        pdf.set_font("Helvetica", size=12)
        pdf.set_fill_color(230, 240, 255)
        pdf.set_draw_color(200, 220, 240)
        pdf.multi_cell(0, 10, "This document certifies that the above file was uploaded and hashed at the stated time.", border=1, fill=True)
        pdf.ln(12)
        pdf.set_font("Helvetica", style="B", size=12)
        pdf.set_text_color(0, 102, 153)
        pdf.cell(0, 10, "Generated by IPLOCAL", ln=True, align="R")

        # Save PDF
        buffer = io.BytesIO()
        pdf_bytes = pdf.output(dest='S').encode('latin1')
        buffer.write(pdf_bytes)
        buffer.seek(0)

    if search_text:
        df = df[df.apply(lambda row: search_text.lower() in row.astype(str).str.lower().to_string(), axis=1)]

    if len(date_range) == 2:
        start, end = date_range
        df = df[(df['timestamp_utc'] >= pd.to_datetime(start)) & (df['timestamp_utc'] <= pd.to_datetime(end))]

    st.dataframe(df, use_container_width=True)

    selected_id = st.selectbox("Select a certificate to download", df["id"].tolist())
    if st.button("📥 Download Selected PDF"):
        with get_connection() as conn:
            cur = conn.cursor()
            cur.execute("SELECT pdf_data FROM certificates WHERE id = %s", (selected_id,))
            pdf_blob = cur.fetchone()[0]
            st.download_button("Download PDF", data=pdf_blob, file_name=f"certificate_{selected_id}.pdf", mime="application/pdf")




